(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   (quote
    (lisp-mode yarn-mode yari yard-mode yahoo-weather xresources-theme xref-js2 writegood-mode window-numbering wgrep web-mode web-beautify vue-mode virtualenvwrapper virtualenv uuidgen uuid utop use-package tuareg toml-mode timonier tide tern-context-coloring tern-auto-complete sx sunshine subatomic-theme ssh sql-indent spaceline-all-the-icons soothe-theme sml-modeline sml-mode smex smartparens smart-mode-line slime slack shell-switcher sentence-navigation scss-mode rustic rust-playground ruby-hash-syntax ruby-end rspec-mode robe rjsx-mode reykjavik-theme restclient rbenv rainbow-delimiters racket-mode quickrun quack pyenv-mode-auto prettier-js persistent-scratch pdf-tools pass pandoc-mode pandoc pallet page-break-lines org-trello org-projectile omnisharp nvm npm-mode nord-theme nodejs-repl nlinum-relative nim-mode nasm-mode mustache-mode muse multi-term mode-icons merlin mastodon markdown-preview-eww makefile-executor madhat2r-theme kubernetes kotlin-mode key-chord julia-shell jsx-mode jsfmt js2-highlight-vars js2-closure js-comint jedi ivy-hydra irony-eldoc insert-shebang inf-mongo indium import-js imenu-list imenu-anywhere iedit ido-vertical-mode ibuffer-vc ibuffer-projectile html-script-src hindent handlebars-mode hackernews gotham-theme gorepl-mode goose-theme google-this go-stacktracer go-projectile go-playground go-imports go-impl go-gopath go-fill-struct go-dlv go-direx go-add-tags gnuplot-mode gnuplot gmail2bbdb git-timemachine git-messenger git-gutter gist ghub ghci-completion ghc-imported-from general geiser gdscript-mode fzf fsharp-mode fontawesome flymd flymake-json flymake-jslint flymake-jshint flymake-hlint flymake-elixir flymake-cursor flylisp flycheck-yamllint flycheck-tip flycheck-rust flycheck-pos-tip flycheck-nim flycheck-irony flycheck-gometalinter flycheck-elixir flycheck-checkbashisms flx-ido flow-minor-mode expand-region exec-path-from-shell evil-surround evil-paredit evil-numbers evil-mu4e evil-mc evil-magit evil-ledger evil-goggles evil-expat evil-exchange evil-dvorak evil-collection evil-colemak-basics evil-avy evil-args evil-anzu eslintd-fix eslint-fix ensime enh-ruby-mode elpy elfeed elein editorconfig dockerfile-mode docker-compose-mode docker diredfl dired-subtree dired-rsync dired-ranger dired-narrow dired-imenu dired-collapse diff-hl dictionary d-mode ctags-update csv-mode counsel-world-clock counsel-projectile corral company-web company-terraform company-tern company-rtags company-racer company-lua company-jedi company-irony-c-headers company-irony company-inf-ruby company-go company-ghci company-ghc company-dcd company-cabal company-c-headers company-anaconda command-queue color-theme colemak-evil closql clojure-quick-repls clojure-cheatsheet clj-refactor caskxy cask-mode cargo calfw-gcal calfw bundler buffer-move bshell browse-kill-ring bpr bbdb-vcard bats-mode bash-completion autopair all-the-icons-ivy alchemist aggressive-indent ag ace-window ace-jump-mode ac-js2 ac-inf-ruby ac-cider))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
