---
- hosts: 127.0.0.1
  connection: local
  remote_user: hugo
  vars:
    home: /home/hugo
    src_home: /home/hugo/git
    applications:
      - google-chrome
      - mongodb
      - minikube
      - audacity
      - calibre
    cli:
      - wget
      - vim
      - neovim
      - ack
      - git
      - the_silver_searcher
      - ripgrep
      - tmux
      - fzf
      - fish
      - fd
      - emacs
      - stow
      - bspwm
      - polybar
      - rofi
      - bat
      - ledger
      - pass
      - nitrogen
      - compton
      - w3m
      - neomutt
      - msmtp
      - arandr
      - aspell
      - ranger
      - docker
      - docker-compose
      - mpd
      - mopidy
      - packer
      - vagrant
      - sxhkd
      - qemu
      - ebtables
      - dnsmasq
      - bridge-utils
      - virt-manager
      - libvirt

  tasks:
    - name: Install cli tools with Pacman
      pacman:
        name: "{{ cli }}"
        state: present
        update_cache: yes
      become: yes
      become_method: sudo

    - name: Clone the suckless simple terminal
      shell: |
        cd /home/hugo/git && git clone https://git.suckless.org/st
        rm -f ./st/config.def.h
        ln -s /home/hugo/snippets/config.def.h /home/hugo/git/st/config.def.h
        cd ./st && make
    - name: Simple Terminal Install
      shell: |
        cd  {{ src_home }}/st && sudo make install
      become: yes
      become_method: sudo

    - name: enable libvirt
      systemd:
        name: libvirtd
        state: started
        enabled: yes
        masked: no
      become: yes
      become_method: sudo

    - name: Vagrant plugins
      shell: |
        vagrant plugin install vagrant-mutate
        vagrant plugin install vagrant-libvirt
