require("lazy").setup({
  "nvim-neotest/nvim-nio",
  "nvim-lua/plenary.nvim",
  "sindrets/diffview.nvim",
  {
    "teal-language/vim-teal",
    ft = "teal",
  },
  "filipdutescu/renamer.nvim",
  { "kevinhwang91/nvim-bqf", ft = "qf" },
  "lewis6991/gitsigns.nvim",
  "LukasPietzschmann/boo.nvim",
  {
    "nvim-tree/nvim-web-devicons",
    config = function()
      require("nvim-web-devicons").setup({ default = true })
    end,
  },
  "hedyhli/outline.nvim",
  "roobert/hoversplit.nvim",
  "folke/neoconf.nvim",
  { "kevinhwang91/nvim-bqf" },
  {
    "GCBallesteros/jupytext.nvim",
    config = true,
  },
  -- "ggandor/leap.nvim",
  require("plugins/which-key"),
  require("plugins/oil"),
  require("plugins/dap"),
  require("plugins/done"),
  require("plugins/mini"),
  require("plugins/nightfox"),
  require("plugins/treesitter"),
  require("plugins/snacks"),
  require("plugins/venv"),
  require("plugins/otter"),
  require("plugins/lspconfig"),
  require("plugins/cmake-tools"),
  require("plugins/lspsaga"),
  require("plugins/none-ls"),
  require("plugins/cmp"),
  require("plugins/codeium"),
  require("plugins/hslens"),
  require("plugins/supermaven"),
  require("plugins/toggleterm"),
  require("plugins/lualine"),
  require("plugins/neogit"),
  require("plugins/iron"),
  require("plugins/overseer"),
  require("plugins/quarto"),
  require("plugins/neotest"),
}, {
  ui = {
    icons = vim.g.have_nerd_font and {} or {
      cmd = "⌘",
      config = "🛠",
      event = "📅",
      ft = "📂",
      init = "⚙",
      keys = "🗝",
      plugin = "🔌",
      runtime = "💻",
      require = "🌙",
      source = "📄",
      start = "🚀",
      task = "📌",
      lazy = "💤 ",
    },
  },
})
