#! /bin/sh
export SXHKD_SHELL=/bin/sh
#xrdb .Xresources
#dropbox start -i
setxkbmap gb -variant colemak
xmodmap $HOME/.Xmodmap

# launch sxhkd
sxhkd -m -1 -t -c $HOME/.config/sxhkd/sxhkdrc $HOME/.config/sxhkd/sxhkdrc_bspwm &

xautolock -disable
# xautolock -detectsleep \
#           -locker   "slock" \
#           -killtime 10 -killer "systemctl suspend" &

bspc monitor -d I II III IV V VI VII VIII
bspc monitor HDMI1 -d IX X
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Emacs state=tiled
bspc rule -a libreoffice state=tiled
bspc rule -a libreoffice-writer state=tiled
bspc rule -a libreoffice-calc state=tiled
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off


compton &
killall nm-applet ; nm-applet &
fluxgui &
dunst &
nitrogen --restore &
$HOME/.config/polybar/launch.sh
# $HOME/.config/mopidy/launch.sh
# emacs --daemon &
