#! /bin/sh
export SXHKD_SHELL=/bin/sh
setxkbmap -variant colemak
sxhkd -m -1 -t &

bspc monitor -d I II III IV V VI VII
bspc monitor HDMI1 -d VIII IX X
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Emacs state=tiled
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off


# compton &
nitrogen --restore &
$HOME/.config/polybar/launch.sh
emacs --daemon &
