return {
  {
    "folke/which-key.nvim",
    event = "VimEnter",
    opts = {
      delay = 0,
      preset = "helix",
      layout = {
        height = { min = 10, max = 25 },
        width = { min = 20, max = 50 },
        spacing = 3,
        align = "left",
      },
      show_help = true,
      icons = {
        -- set icon mappings to true if you have a Nerd Font
        mappings = vim.g.have_nerd_font,
        -- If you are using a Nerd Font: set icons.keys to an empty table which will use the
        -- default which-key.nvim defined Nerd Font icons, otherwise define a string table
        keys = vim.g.have_nerd_font and {} or {
          Up = "<Up> ",
          Down = "<Down> ",
          Left = "<Left> ",
          Right = "<Right> ",
          C = "<C-…> ",
          M = "<M-…> ",
          D = "<D-…> ",
          S = "<S-…> ",
          CR = "<CR> ",
          Esc = "<Esc> ",
          ScrollWheelDown = "<ScrollWheelDown> ",
          ScrollWheelUp = "<ScrollWheelUp> ",
          NL = "<NL> ",
          BS = "<BS> ",
          Space = "<Space> ",
          Tab = "<Tab> ",
          F1 = "<F1>",
          F2 = "<F2>",
          F3 = "<F3>",
          F4 = "<F4>",
          F5 = "<F5>",
          F6 = "<F6>",
          F7 = "<F7>",
          F8 = "<F8>",
          F9 = "<F9>",
          F10 = "<F10>",
          F11 = "<F11>",
          F12 = "<F12>",
        },
      },

      spec = {
        { "<leader>c",  group = "[C]ode",            mode = { "n", "x" } },
        { "<leader>d",  group = "[D]ocument" },
        { "<leader>r",  group = "[R]ename" },
        { "<leader>s",  group = "[S]earch" },
        { "<leader>w",  group = "[W]orkspace" },
        { "<leader>wh", desc = "Previous Tab" },
        { "<leader>wi", desc = "Next Tab" },
        { "<leader>wH", desc = "First Tab" },
        { "<leader>wI", desc = "Last Tab" },
        { "<leader>t",  group = "[T]oggle" },
        { "<leader>T",  group = "[T]erminal" },
        { "<leader>h",  group = "Git [H]unk",        mode = { "n", "v" } },
        { "<leader><leader>", desc = "Workspace Palette" },
        { "<leader>ca", desc = "Code Action Palette", mode = { "n", "x" } },
        { "<leader>cF", desc = "Format Buffer" },
        { "<leader>co", desc = "Organize Imports" },
        { "<leader>cx", desc = "Fix All" },
        { "<leader>ch", desc = "Config Health" },
        { "<leader>cp", desc = "Config Profile" },
        { "<leader>cr", desc = "Config Reload" },
        { "<leader>cc", group = "[C]ode [C]ompanion" },
        { "<leader>k",  group = "[K]Tests" },
        { "<leader>kp", desc = "Task Palette" },
        { "<leader>kn", desc = "Test Nearest" },
        { "<leader>kr", desc = "Run Project Tests" },
        { "<leader>kR", desc = "Run Project App" },
        { "<leader>kb", desc = "Build/Render Project" },
        { "<leader>kF", desc = "Format Project" },
        { "<leader>kd", desc = "Debug Nearest Test" },
        { "<leader>l",  group = "[L]SP" },
        { "<leader>ld", desc = "Diagnostic Palette" },
        { "<leader>lX", desc = "Toggle Diagnostics" },
        { "<leader>lS", desc = "Diagnostic Summary" },
        { "<leader>p",  group = "[P]rojects" },
        { "<leader>pl", desc = "Load Project Session" },
        { "<leader>ps", desc = "Save Project Session" },
        { "<leader>pS", desc = "Select Session" },
        { "<leader>aP", desc = "AI Palette", mode = { "n", "x" } },
        { "<leader>ap", group = "[P]i coding agent" },
        { "<leader>apt", desc = "Toggle pi" },
        { "<leader>apf", desc = "Focus pi" },
        { "<leader>apl", desc = "Login (saml2aws)" },
        { "<leader>ai", group = "[A]ider [A]I" },
        { "<leader>ai/", desc = "Toggle Aider" },
        { "<leader>ais", desc = "Send to Aider" },
        { "<leader>aic", desc = "Aider Commands" },
        { "<leader>aib", desc = "Send Buffer" },
        { "<leader>ai+", desc = "Add File" },
        { "<leader>ai-", desc = "Drop File" },
        { "<leader>air", desc = "Add Read-Only" },
        { "<leader>aiR", desc = "Reset Session" },
        { "<leader>aa", group = "[A]vante [A]I" },
        { "<leader>aaa", desc = "Ask AI" },
        { "<leader>aan", desc = "New Ask" },
        { "<leader>aam", desc = "Full View Ask" },
        { "<leader>aae", desc = "Edit with AI" },
        { "<leader>aar", desc = "Refresh" },
        { "<leader>aaf", desc = "Focus Sidebar" },
        { "<leader>aaS", desc = "Stop Generation" },
        { "<leader>aat", desc = "Toggle Sidebar" },
        { "<leader>aad", desc = "Toggle Debug" },
        { "<leader>aaC", desc = "Toggle Selection" },
        { "<leader>aas", desc = "Toggle Suggestions" },
        { "<leader>aaR", desc = "Toggle Repo Map" },
        { "<leader>aac", desc = "Add Current Buffer" },
        { "<leader>aaB", desc = "Add All Buffers" },
        { "<leader>aa?", desc = "Select Model" },
        { "<leader>aah", desc = "Select History" },
      },
    },
  },
}
-- vim: ts=2 sts=2 sw=2 et
