return {
  dir = vim.fn.stdpath("config"),
  name = "workflow-local",
  lazy = true,
  cmd = {
    "WorkspacePalette",
    "ProjectInfo",
    "ProjectRoot",
    "ConfigEdit",
    "AiPalette",
    "PiToggle",
    "PiFocus",
    "PiLogin",
    "CodePalette",
    "LspOrganizeImports",
    "LspFixAll",
    "TaskPalette",
    "ProjectTest",
    "ProjectRun",
    "ProjectBuild",
    "ProjectFormat",
    "DiagnosticPalette",
    "DiagnosticSummary",
    "SuppressDiagnostic",
    "SuppressDiagnosticAbove",
    "SuppressDiagnosticFile",
    "UnsuppressDiagnostic",
    "ConfigHealth",
    "ConfigProfile",
    "ConfigReload",
    "SessionSaveProject",
    "SessionLoadProject",
    "SessionSelect",
  },
  keys = {
    { "<leader><leader>", desc = "Workspace palette" },
    { "<leader>aP", mode = { "n", "v" }, desc = "AI palette" },
    { "<leader>apt", desc = "Toggle pi" },
    { "<leader>apf", desc = "Focus pi" },
    { "<leader>apl", desc = "Login (saml2aws)" },
    { "<leader>ca", mode = { "n", "v" }, desc = "Code action palette" },
    { "<leader>cF", desc = "Format buffer" },
    { "<leader>co", desc = "Organize imports" },
    { "<leader>cx", desc = "Fix all" },
    { "<leader>kn", desc = "Test nearest" },
    { "<leader>kf", desc = "Test file" },
    { "<leader>ka", desc = "Test suite" },
    { "<leader>kd", desc = "Debug nearest test" },
    { "<leader>kD", desc = "Debug file tests" },
    { "<leader>kr", desc = "Run project tests" },
    { "<leader>kR", desc = "Run project app" },
    { "<leader>kb", desc = "Build/render project" },
    { "<leader>kF", desc = "Format project" },
    { "<leader>kp", desc = "Task palette" },
    { "<leader>ld", desc = "Diagnostic palette" },
    { "<leader>lX", desc = "Toggle diagnostics" },
    { "<leader>lC", desc = "Diagnostic summary" },
    { "<leader>lxs", desc = "Suppress diagnostic inline" },
    { "<leader>lxS", desc = "Suppress diagnostic above" },
    { "<leader>lxf", desc = "Suppress diagnostic file" },
    { "<leader>lxu", desc = "Remove diagnostic suppression" },
    { "<leader>lxi", desc = "Suppress diagnostic interactive" },
    { "<leader>lxl", desc = "List diagnostic suppressions" },
    { "<leader>pl", desc = "Load project session" },
    { "<leader>pS", desc = "Select session" },
    { "<leader>ch", desc = "Config health" },
    { "<leader>cp", desc = "Config profile" },
    { "<leader>cr", desc = "Config reload" },
  },
  config = function()
    require("workflows").setup()
  end,
}
