export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:$HOME/.local/share/bin
export PATH="~/.pyenv/bin:$PATH"
export PATH="/home/hugo/.cask/bin:$PATH"
export GOPATH="/home/hugo/git/simba/go"
export PATH="$GOPATH/bin:$PATH"
source $HOME/.cargo/env
export PYENV_VIRTUALENVWRAPPER_PREFER_PYVENV="true"
export PATH="$HOME/.rbenv/shims:$PATH"
