# exports
export ZSH="$HOME/.oh-my-zsh"
export SSH_ENV="$HOME/.ssh/environment"
export PATH="$PATH:/usr/local/go/bin"
export PATH="$PATH:$HOME/.local/share/bin"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$HOME/.pyenv/bin:$PATH"
export PATH="$HOME/.cask/bin:$PATH"
export GOPATH="$HOME/git/newsuk/go"
export PATH="$GOPATH/bin:$PATH"
export NVM_DIR="$HOME/.nvm"
export PYENV_VIRTUALENVWRAPPER_PREFER_PYVENV="true"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.rbenv/bin:$PATH"
export PATH="$HOME/.rbenv/shims:$PATH"
export EDITOR="nvim"
export ARCHFLAGS="-arch x86_64"
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
export GTAGSCONF=~/.gtags.conf
export GTAGSLABEL=pygments
export PATH="$HOME/.rbenv/versions/2.5.3/bin:$PATH"
. "$HOME/.cargo/env"
